LD_NAMES = [\
'CONTOUR_CHIN',
'CONTOUR_LEFT1',
'CONTOUR_LEFT2',
'CONTOUR_LEFT3',
'CONTOUR_LEFT4',
'CONTOUR_LEFT5',
'CONTOUR_LEFT6',
'CONTOUR_LEFT7',
'CONTOUR_LEFT8',
'CONTOUR_LEFT9',
'CONTOUR_RIGHT1',
'CONTOUR_RIGHT2',
'CONTOUR_RIGHT3',
'CONTOUR_RIGHT4',
'CONTOUR_RIGHT5',
'CONTOUR_RIGHT6',
'CONTOUR_RIGHT7',
'CONTOUR_RIGHT8',
'CONTOUR_RIGHT9',
'LEFTEYE_BOTTOM',
'LEFTEYE_LEFTCORNER',
'LEFTEYE_LOWERLEFTQUARTER',
'LEFTEYE_LOWERRIGHTQUARTER',
'LEFTEYE_PUPIL',
'LEFTEYE_RIGHTCORNER',
'LEFTEYE_TOP',
'LEFTEYE_UPPERLEFTQUARTER',
'LEFTEYE_UPPERRIGHTQUARTER',
'LEFTEYEBROW_LEFTCORNER',
'LEFTEYEBROW_LOWERLEFTQUARTER',
'LEFTEYEBROW_LOWERMIDDLE',
'LEFTEYEBROW_LOWERRIGHTQUARTER',
'LEFTEYEBROW_RIGHTCORNER',
'LEFTEYEBROW_UPPERLEFTQUARTER',
'LEFTEYEBROW_UPPERMIDDLE',
'LEFTEYEBROW_UPPERRIGHTQUARTER',
'MOUTH_LEFTCORNER',
'MOUTH_LOWERLIPBOTTOM',
'MOUTH_LOWERLIPLEFTCONTOUR1',
'MOUTH_LOWERLIPLEFTCONTOUR2',
'MOUTH_LOWERLIPLEFTCONTOUR3',
'MOUTH_LOWERLIPRIGHTCONTOUR1',
'MOUTH_LOWERLIPRIGHTCONTOUR2',
'MOUTH_LOWERLIPRIGHTCONTOUR3',
'MOUTH_LOWERLIPTOP',
'MOUTH_RIGHTCORNER',
'MOUTH_UPPERLIPBOTTOM',
'MOUTH_UPPERLIPLEFTCONTOUR1',
'MOUTH_UPPERLIPLEFTCONTOUR2',
'MOUTH_UPPERLIPLEFTCONTOUR3',
'MOUTH_UPPERLIPRIGHTCONTOUR1',
'MOUTH_UPPERLIPRIGHTCONTOUR2',
'MOUTH_UPPERLIPRIGHTCONTOUR3',
'MOUTH_UPPERLIPTOP',
'NOSE_CONTOURLEFT1',
'NOSE_CONTOURLEFT2',
'NOSE_CONTOURLEFT3',
'NOSE_CONTOURLOWERMIDDLE',
'NOSE_CONTOURRIGHT1',
'NOSE_CONTOURRIGHT2',
'NOSE_CONTOURRIGHT3',
'NOSE_LEFT',
'NOSE_RIGHT',
'NOSE_TIP',
'RIGHTEYE_BOTTOM',
'RIGHTEYE_LEFTCORNER',
'RIGHTEYE_LOWERLEFTQUARTER',
'RIGHTEYE_LOWERRIGHTQUARTER',
'RIGHTEYE_PUPIL',
'RIGHTEYE_RIGHTCORNER',
'RIGHTEYE_TOP',
'RIGHTEYE_UPPERLEFTQUARTER',
'RIGHTEYE_UPPERRIGHTQUARTER',
'RIGHTEYEBROW_LEFTCORNER',
'RIGHTEYEBROW_LOWERLEFTQUARTER',
'RIGHTEYEBROW_LOWERMIDDLE',
'RIGHTEYEBROW_LOWERRIGHTQUARTER',
'RIGHTEYEBROW_RIGHTCORNER',
'RIGHTEYEBROW_UPPERLEFTQUARTER',
'RIGHTEYEBROW_UPPERMIDDLE',
'RIGHTEYEBROW_UPPERRIGHTQUARTER']

ld_names = \
['contour_chin',\
 'contour_left1',\
 'contour_left2',\
 'contour_left3',\
 'contour_left4',\
 'contour_left5',\
 'contour_left6',\
 'contour_left7',\
 'contour_left8',\
 'contour_left9',\
 'contour_right1',\
 'contour_right2',\
 'contour_right3',\
 'contour_right4',\
 'contour_right5',\
 'contour_right6',\
 'contour_right7',\
 'contour_right8',\
 'contour_right9',\
 'left_eye_bottom',\
 'left_eye_left_corner',\
 'left_eye_lower_left_quarter',\
 'left_eye_lower_right_quarter',\
 'left_eye_pupil',\
 'left_eye_right_corner',\
 'left_eye_top',\
 'left_eye_upper_left_quarter',\
 'left_eye_upper_right_quarter',\
 'left_eyebrow_left_corner',\
 'left_eyebrow_lower_left_quarter',\
 'left_eyebrow_lower_middle',\
 'left_eyebrow_lower_right_quarter',\
 'left_eyebrow_right_corner',\
 'left_eyebrow_upper_left_quarter',\
 'left_eyebrow_upper_middle',\
 'left_eyebrow_upper_right_quarter',\
 'mouth_left_corner',\
 'mouth_lower_lip_bottom',\
 'mouth_lower_lip_left_contour1',\
 'mouth_lower_lip_left_contour2',\
 'mouth_lower_lip_left_contour3',\
 'mouth_lower_lip_right_contour1',\
 'mouth_lower_lip_right_contour2',\
 'mouth_lower_lip_right_contour3',\
 'mouth_lower_lip_top',\
 'mouth_right_corner',\
 'mouth_upper_lip_bottom',\
 'mouth_upper_lip_left_contour1',\
 'mouth_upper_lip_left_contour2',\
 'mouth_upper_lip_left_contour3',\
 'mouth_upper_lip_right_contour1',\
 'mouth_upper_lip_right_contour2',\
 'mouth_upper_lip_right_contour3',\
'mouth_upper_lip_top',\
 'nose_contour_left1',\
 'nose_contour_left2',\
 'nose_contour_left3',\
 'nose_contour_lower_middle',\
 'nose_contour_right1',\
 'nose_contour_right2',\
 'nose_contour_right3',\
 'nose_left',\
 'nose_right',\
 'nose_tip',\
 'right_eye_bottom',\
 'right_eye_left_corner',\
 'right_eye_lower_left_quarter',\
 'right_eye_lower_right_quarter',\
 'right_eye_pupil',\
 'right_eye_right_corner',\
 'right_eye_top',\
 'right_eye_upper_left_quarter',\
 'right_eye_upper_right_quarter',\
 'right_eyebrow_left_corner',\
 'right_eyebrow_lower_left_quarter',\
 'right_eyebrow_lower_middle',\
 'right_eyebrow_lower_right_quarter',\
 'right_eyebrow_right_corner',\
 'right_eyebrow_upper_left_quarter',\
 'right_eyebrow_upper_middle',\
 'right_eyebrow_upper_right_quarter']
